name: Build plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: logseq-plugin-for-misskey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp -r document dist index.html icon_ki.png README.md package.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> "$GITHUB_ENV"

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          allowUpdates: true
          draft: false
          prerelease: false

      - name: Create and upload release
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./${{ env.PLUGIN_NAME }}-${{ env.tag_name }}.zip, ./package.json
          tag_name: ${{ steps.build.outputs.tag_name }}
          name: ${{ env.PLUGIN_NAME }}-${{ env.tag_name }}
          body: Release ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}